spring.application.name=personal-finance-api

# Configurações do Banco H2
spring.datasource.url=jdbc:h2:mem:finance_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o Console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra o SQL gerado pelo Hibernate no console do IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true