spring.application.name=personal-finance-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET}
api.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost}

spring.flyway.url=${DB_URL}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.user=${DB_USER}
spring.flyway.enabled=true
flyway.locations=filesystem:src/main/resources/db/migration
logging.level.org.flywaydb=DEBUG

# Mostra o SQL gerado pelo Hibernate no console do IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=true